# Generated by Django 3.2.3 on 2021-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actovipoln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeract', models.PositiveIntegerField()),
                ('dateact', models.DateField()),
                ('statusact', models.CharField(max_length=100)),
                ('dates', models.DateField()),
                ('datepo', models.DateField()),
            ],
            options={
                'verbose_name': 'Акт о выполненной работе',
                'verbose_name_plural': 'Акт о выполненной работе',
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerdog', models.PositiveIntegerField()),
                ('statusdog', models.CharField(max_length=100)),
                ('stoimost', models.PositiveIntegerField()),
                ('osobusl', models.PositiveIntegerField()),
                ('datesostdog', models.DateField(max_length=100)),
                ('daterastdog', models.DateField()),
                ('datenachdog', models.DateField()),
                ('dateokonchdog', models.DateField(default=False)),
                ('datepodpdog', models.DateField(default=False)),
                ('prichrast', models.BooleanField(default=False)),
                ('kod_sotr', models.PositiveIntegerField()),
                ('kod_ts', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Putlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerdog', models.PositiveIntegerField()),
                ('nomerputlist', models.PositiveIntegerField()),
                ('datesostputlist', models.DateField()),
                ('statusputlist', models.CharField(max_length=100)),
                ('dateviezd', models.DateField()),
                ('nachpokazodo', models.PositiveIntegerField()),
                ('datevozvr', models.DateField()),
                ('konechpokazodo', models.PositiveIntegerField()),
                ('ostgoruchviezd', models.PositiveIntegerField()),
                ('ostgoruchvozvr', models.PositiveIntegerField()),
                ('srokputlist', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ттн',
                'verbose_name_plural': 'ттн',
            },
        ),
        migrations.CreateModel(
            name='Schetfact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerschetfact', models.PositiveIntegerField()),
                ('datesostschetfact', models.DateField()),
                ('statusschetfact', models.CharField(max_length=100)),
                ('nalstav', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'Счет фактура',
                'verbose_name_plural': 'Счет фактура',
            },
        ),
        migrations.CreateModel(
            name='Schetopl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerschet', models.PositiveIntegerField()),
                ('dateschet', models.DateField()),
                ('statusschet', models.CharField(max_length=100)),
                ('nomerschetpoluch', models.PositiveIntegerField()),
                ('summa', models.PositiveIntegerField()),
                ('poluchatel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счет на оплату',
            },
        ),
        migrations.CreateModel(
            name='SprDolgn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimdolgn', models.CharField(max_length=100, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='SprGorod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimgorod', models.CharField(max_length=100, verbose_name='Наименование города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='SprGruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimgruza', models.CharField(max_length=100, verbose_name='Наименование груза')),
                ('edizm', models.CharField(max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='SprMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimmarka', models.CharField(max_length=100, verbose_name='Наименование марки тс')),
            ],
            options={
                'verbose_name': 'Марка тс',
                'verbose_name_plural': 'Марки тс',
            },
        ),
        migrations.CreateModel(
            name='SprModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimmodel', models.CharField(max_length=100, verbose_name='Наименование модели тс')),
            ],
            options={
                'verbose_name': 'Модель тс',
                'verbose_name_plural': 'Модели тс',
            },
        ),
        migrations.CreateModel(
            name='SprOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimorg', models.CharField(max_length=100, verbose_name='Наименование рганизации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='SprSotr',
            fields=[
                ('kod_sotr', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код сотрудника')),
                ('daterogd', models.DateField(verbose_name='Дата рождения')),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otch', models.CharField(max_length=50, verbose_name='Отчество')),
                ('datenaim', models.DateField()),
                ('dateokonch', models.DateField()),
                ('dolgn', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SprTipgruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimtipgruza', models.CharField(max_length=100, verbose_name='Наименование типа груза')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы груза',
            },
        ),
        migrations.CreateModel(
            name='SprTovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimtovar', models.CharField(max_length=100, verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SprUlici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimulici', models.CharField(max_length=100, verbose_name='Наименование улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='SprVidharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimharts', models.CharField(max_length=100, verbose_name='Наименование характеристики ТС')),
            ],
            options={
                'verbose_name': 'Наименование характеристики ТС',
                'verbose_name_plural': 'Наименование характеристик ТС',
            },
        ),
        migrations.CreateModel(
            name='SprVidts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimvidts', models.CharField(max_length=100, verbose_name='Наименование вида ТС')),
            ],
            options={
                'verbose_name': 'Вид тс',
                'verbose_name_plural': 'Виды тс',
            },
        ),
        migrations.CreateModel(
            name='Trsredstvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosnomer', models.CharField(max_length=10, verbose_name='Гос номер')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Ttn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerttn', models.PositiveIntegerField()),
                ('datettn', models.DateField()),
                ('statusttn', models.CharField(max_length=100)),
                ('kolvoplan', models.PositiveIntegerField()),
                ('kolvofact', models.PositiveIntegerField()),
                ('edizmttn', models.CharField(max_length=100)),
                ('srokdost', models.DateField(max_length=100)),
                ('itogstoim', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'ттн',
                'verbose_name_plural': 'ттн',
            },
        ),
        migrations.CreateModel(
            name='Uchastnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viduch', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('inn', models.PositiveIntegerField()),
                ('kpp', models.PositiveIntegerField()),
                ('kontlico', models.CharField(max_length=100)),
                ('tel', models.PositiveIntegerField()),
                ('statusuch', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Zaiavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerzai', models.CharField(max_length=100)),
                ('datezai', models.DateField()),
                ('gruzopr', models.CharField(max_length=100)),
                ('gruzpoluch', models.CharField(max_length=100)),
                ('adr_gruzopr', models.CharField(max_length=100)),
                ('adr_gruzpoluch', models.CharField(max_length=100)),
                ('datepogr', models.DateField()),
                ('daterazgr', models.CharField(max_length=100)),
                ('statuszai', models.CharField(max_length=100)),
                ('zakazch', models.CharField(max_length=100)),
                ('naimgruza', models.CharField(max_length=100)),
                ('edizm', models.CharField(max_length=100)),
                ('kolvo', models.PositiveIntegerField()),
                ('tipgruza', models.CharField(max_length=100)),
                ('massa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('gabdlina', models.DecimalField(decimal_places=2, max_digits=2)),
                ('gabshir', models.DecimalField(decimal_places=2, max_digits=2)),
                ('gabvisot', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
