# Generated by Django 3.2.3 on 2021-06-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerzai', models.CharField(max_length=100)),
                ('nomerdog', models.IntegerField()),
                ('statusdog', models.CharField(max_length=100)),
                ('stoimost', models.CharField(max_length=50)),
                ('osobusl', models.CharField(blank=True, max_length=500, null=True)),
                ('datesostdog', models.DateField()),
                ('daterastdog', models.DateField(blank=True, null=True)),
                ('datenachdog', models.DateField()),
                ('dateokonchdog', models.DateField()),
                ('datepodpdog', models.DateField()),
                ('prichrast', models.CharField(blank=True, max_length=100, null=True)),
                ('fiosotr', models.CharField(max_length=50)),
                ('marka', models.CharField(blank=True, max_length=50)),
                ('gosnomer', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='SprDolgn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimdolgn', models.CharField(max_length=100, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='SprGorod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimgorod', models.CharField(max_length=100, verbose_name='Наименование города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='SprGruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimgruza', models.CharField(max_length=100, verbose_name='Наименование груза')),
                ('edizm', models.CharField(max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='SprMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimmarka', models.CharField(max_length=100, verbose_name='Наименование марки тс')),
            ],
            options={
                'verbose_name': 'Марка тс',
                'verbose_name_plural': 'Марки тс',
            },
        ),
        migrations.CreateModel(
            name='SprModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimmodel', models.CharField(max_length=100, verbose_name='Наименование модели тс')),
                ('naimmarka', models.CharField(default='', max_length=100, verbose_name='Наименование марки тс')),
            ],
            options={
                'verbose_name': 'Модель тс',
                'verbose_name_plural': 'Модели тс',
            },
        ),
        migrations.CreateModel(
            name='SprOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimorg', models.CharField(max_length=100, verbose_name='Наименование рганизации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='SprSotr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_sotr', models.CharField(max_length=100, verbose_name='Код сотрудника')),
                ('daterogd', models.DateField()),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otch', models.CharField(max_length=50)),
                ('datenaim', models.DateField()),
                ('dateokonch', models.DateField(blank=True, null=True)),
                ('dolgn', models.CharField(max_length=50)),
                ('pasport', models.CharField(max_length=50)),
                ('vodud', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SprTipgruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimtipgruza', models.CharField(max_length=100, verbose_name='Наименование типа груза')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы груза',
            },
        ),
        migrations.CreateModel(
            name='SprTovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimtovar', models.CharField(max_length=100, verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SprUlici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimulici', models.CharField(max_length=100, verbose_name='Наименование улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='SprVidharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimharts', models.CharField(max_length=100, verbose_name='Наименование характеристики ТС')),
            ],
            options={
                'verbose_name': 'Наименование характеристики ТС',
                'verbose_name_plural': 'Наименование характеристик ТС',
            },
        ),
        migrations.CreateModel(
            name='SprVidts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimvidts', models.CharField(max_length=100, verbose_name='Наименование вида ТС')),
            ],
            options={
                'verbose_name': 'Вид тс',
                'verbose_name_plural': 'Виды тс',
            },
        ),
        migrations.CreateModel(
            name='Trsredstvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_ts', models.CharField(blank=True, max_length=10, verbose_name='Гос номер')),
                ('gosnomer', models.CharField(max_length=10, verbose_name='Гос номер')),
                ('naimmodel', models.CharField(default='', max_length=100, verbose_name='Наименование модели тс')),
                ('naimmarka', models.CharField(default='', max_length=100, verbose_name='Наименование марки тс')),
                ('naimvidts', models.CharField(default='', max_length=100, verbose_name='Наименование вида ТС')),
                ('tipkuzova', models.CharField(default='', max_length=100, verbose_name='Тип кузова')),
                ('gabdlina', models.CharField(default='', max_length=100, verbose_name='Габариты длина')),
                ('gabshir', models.CharField(default='', max_length=100, verbose_name='Габариты ширина')),
                ('gabvis', models.CharField(default='', max_length=100, verbose_name='Габариты высота')),
                ('maxdopustmassa', models.CharField(default='', max_length=100, verbose_name='Максимально допустимая масса')),
                ('sposobpogr', models.CharField(default='', max_length=100, verbose_name='Способ погрузки')),
            ],
            options={
                'verbose_name': 'Спр.транспортное средство',
                'verbose_name_plural': 'Спр.транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='Uchastnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viduch', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=50)),
                ('kpp', models.CharField(max_length=50)),
                ('kontlico', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Zaiavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerzai', models.CharField(max_length=50)),
                ('datezai', models.DateField()),
                ('gruzopr', models.CharField(max_length=100)),
                ('gruzpoluch', models.CharField(max_length=100)),
                ('adr_gruzopr', models.CharField(max_length=100)),
                ('adr_gruzpoluch', models.CharField(max_length=100)),
                ('datepogr', models.DateField()),
                ('daterazgr', models.DateField()),
                ('statuszai', models.CharField(max_length=100)),
                ('zakazch', models.CharField(max_length=100)),
                ('naimgruza', models.CharField(max_length=100)),
                ('edizm', models.CharField(max_length=100)),
                ('kolvo', models.CharField(max_length=50)),
                ('tipgruza', models.CharField(max_length=100)),
                ('massa', models.CharField(max_length=50)),
                ('gabdlina', models.CharField(max_length=50)),
                ('gabshir', models.CharField(max_length=50)),
                ('gabvisot', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Ttn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerttn', models.CharField(max_length=50)),
                ('datettn', models.DateField()),
                ('statusttn', models.CharField(max_length=100)),
                ('kolvoplan', models.CharField(max_length=50)),
                ('kolvofact', models.CharField(max_length=50)),
                ('edizmttn', models.CharField(max_length=100)),
                ('srokdost', models.DateField()),
                ('itogstoim', models.CharField(max_length=50)),
                ('nomerdog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.dogovor')),
            ],
            options={
                'verbose_name': 'ттн',
                'verbose_name_plural': 'ттн',
            },
        ),
        migrations.CreateModel(
            name='Schetopl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerschet', models.CharField(max_length=50)),
                ('dateschet', models.DateField()),
                ('statusschet', models.CharField(max_length=100)),
                ('nomerschetpoluch', models.CharField(max_length=50)),
                ('summa', models.CharField(max_length=50)),
                ('poluchatel', models.CharField(max_length=100)),
                ('zakazch', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('schetbanka', models.CharField(blank=True, max_length=100)),
                ('bik', models.CharField(blank=True, max_length=100)),
                ('sostavil', models.CharField(blank=True, max_length=100)),
                ('nomerdog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruzi.dogovor')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счет на оплату',
            },
        ),
        migrations.CreateModel(
            name='Schetfact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerschetfact', models.CharField(max_length=50)),
                ('datesostschetfact', models.DateField()),
                ('statusschetfact', models.CharField(max_length=100)),
                ('nalstav', models.CharField(max_length=50)),
                ('stoimostt', models.CharField(max_length=50)),
                ('datepodpschetfact', models.DateField()),
                ('sostschetfact', models.CharField(max_length=100)),
                ('nomerdog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.dogovor')),
            ],
            options={
                'verbose_name': 'Счет фактура',
                'verbose_name_plural': 'Счет фактуры',
            },
        ),
        migrations.CreateModel(
            name='Putlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerputlist', models.CharField(max_length=50)),
                ('datesostputlist', models.DateField()),
                ('statusputlist', models.CharField(max_length=100)),
                ('dateviezd', models.DateField()),
                ('nachpokazodo', models.CharField(max_length=50)),
                ('datevozvr', models.DateField()),
                ('konechpokazodo', models.CharField(max_length=50)),
                ('ostgoruchviezd', models.CharField(max_length=50)),
                ('ostgoruchvozvr', models.CharField(max_length=50)),
                ('srokputlist', models.CharField(max_length=100)),
                ('datepodpputlist', models.DateField()),
                ('osobotm', models.CharField(max_length=100)),
                ('nomerdog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.dogovor')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
            },
        ),
        migrations.CreateModel(
            name='Actovipoln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeract', models.CharField(max_length=100)),
                ('dateact', models.DateField()),
                ('statusact', models.CharField(max_length=100)),
                ('dates', models.DateField()),
                ('datepo', models.DateField()),
                ('pretenz', models.CharField(blank=True, max_length=100)),
                ('datepodpis', models.DateField(blank=True, null=True)),
                ('zakazch', models.CharField(blank=True, max_length=100)),
                ('fios', models.CharField(blank=True, max_length=100)),
                ('nomerdog', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gruzi.dogovor')),
            ],
            options={
                'verbose_name': 'Акт о выполненной работе',
                'verbose_name_plural': 'Акты о выполненной работе',
            },
        ),
    ]
