# Generated by Django 3.2.3 on 2021-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprsotr',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='prichrast',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='daterogd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='fam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='kod_sotr',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='otch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uchastnik',
            name='statusuch',
            field=models.CharField(max_length=100),
        ),
    ]
