# Generated by Django 3.2.3 on 2021-05-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0002_auto_20210530_1417'),
        ('gruzi', '0002_auto_20210531_0301'),
    ]

    operations = [
    ]
