# Generated by Django 3.2.3 on 2021-06-18 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0003_auto_20210618_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actovipoln',
            name='fios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.sprsotr'),
        ),
        migrations.AlterField(
            model_name='actovipoln',
            name='nomerdog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.dogovor'),
        ),
        migrations.AlterField(
            model_name='actovipoln',
            name='zakazch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.sprorg'),
        ),
    ]
