# Generated by Django 3.2.3 on 2021-05-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0003_merge_0002_auto_20210530_1417_0002_auto_20210531_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='daterastdog',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='osobusl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='prichrast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='dateokonch',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='kod_sotr',
            field=models.CharField(max_length=100, verbose_name='Код сотрудника'),
        ),
    ]
