# Generated by Django 3.2.3 on 2021-05-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0004_auto_20210531_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='daterastdog',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='osobusl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='prichrast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
