# Generated by Django 3.2.3 on 2021-06-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0004_auto_20210618_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttn',
            name='nomerdog',
        ),
        migrations.AlterField(
            model_name='sprsotr',
            name='dolgn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.sprdolgn'),
        ),
    ]
