# Generated by Django 3.2.3 on 2021-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0005_auto_20210531_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='trsredstvo',
            name='kod_ts',
            field=models.CharField(blank=True, max_length=10, verbose_name='Гос номер'),
        ),
    ]
