# Generated by Django 3.2.3 on 2021-06-18 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0005_auto_20210618_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttn',
            name='nomerdog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gruzi.dogovor'),
        ),
    ]
