# Generated by Django 3.2.3 on 2021-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0006_trsredstvo_kod_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogovor',
            old_name='kod_sotr',
            new_name='fiosotr',
        ),
        migrations.RemoveField(
            model_name='dogovor',
            name='kod_ts',
        ),
        migrations.AddField(
            model_name='dogovor',
            name='datezai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='gosnomer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='marka',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
