# Generated by Django 3.2.3 on 2021-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0007_auto_20210531_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actovipoln',
            options={'verbose_name': 'Акт о выполненной работе', 'verbose_name_plural': 'Акты о выполненной работе'},
        ),
        migrations.AlterModelOptions(
            name='dogovor',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договора'},
        ),
        migrations.AlterModelOptions(
            name='putlist',
            options={'verbose_name': 'Путевой лист', 'verbose_name_plural': 'Путевые листы'},
        ),
        migrations.AlterModelOptions(
            name='schetfact',
            options={'verbose_name': 'Счет фактура', 'verbose_name_plural': 'Счет фактуры'},
        ),
        migrations.AddField(
            model_name='actovipoln',
            name='datepodpis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actovipoln',
            name='fios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='actovipoln',
            name='pretenz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='actovipoln',
            name='zakazch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schetopl',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schetopl',
            name='nomerdog',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schetopl',
            name='schetbanka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schetopl',
            name='sostavil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schetopl',
            name='zakazch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
