# Generated by Django 3.2.3 on 2021-06-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0009_auto_20210621_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trsredstvo',
            name='tipkuzova',
            field=models.CharField(choices=[('Tent', 'Тентованный'), ('Celnmet', 'Цельнометаллический'), ('Promtov', 'Промтоварный'), ('Izimetr', 'Изометрический'), ('Refrejir', 'Рефрежиратор'), ('Cest', 'Цистерна')], default='', max_length=100, verbose_name='Тип кузова'),
        ),
    ]
