# Generated by Django 3.2.3 on 2021-06-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0010_alter_trsredstvo_tipkuzova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schetfact',
            name='sostschetfact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruzi.sprsotr'),
        ),
    ]
