# Generated by Django 3.2.3 on 2021-06-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0011_alter_schetfact_sostschetfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='schetopl',
            name='datepodpisschetopl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schetfact',
            name='statusschetfact',
            field=models.CharField(choices=[('trebpodp', 'Требуется подпись'), ('podpis', 'Подписанный')], max_length=100),
        ),
    ]
