# Generated by Django 3.2.3 on 2021-06-21 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0012_auto_20210621_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schetopl',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruzi.sprorg'),
        ),
        migrations.AlterField(
            model_name='schetopl',
            name='poluchatel',
            field=models.CharField(default='ИП Мельниченко Наталья Александровна', max_length=100),
        ),
        migrations.AlterField(
            model_name='schetopl',
            name='statusschet',
            field=models.CharField(choices=[('ozidopl', 'Ожидает оплаты'), ('opl', 'Оплачен')], max_length=100),
        ),
    ]
