# Generated by Django 3.2.3 on 2021-06-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruzi', '0013_auto_20210621_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttn',
            name='naimgruz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gruzi.sprgruza'),
        ),
        migrations.AlterField(
            model_name='putlist',
            name='statusputlist',
            field=models.CharField(choices=[('sost', 'Составлен'), ('priniat', 'Принят')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='statusttn',
            field=models.CharField(default='Принята', max_length=100),
        ),
    ]
